### ISSUE TITLE
Pysandbox in celery

### ISSUE THREAD

**Issue by darbula** [openjudge/sandbox#17]
I'm having an issue with pysandbox (0.3.5-3) running as celery task. Namely when trying to trigger time limit using loop.c from test suite, task is never done, when killed sandbox returns cpu time greater than the limit. Task is using MinimalPolicy from the test suite and other limits are detected as expected.

**Comment by darbula** [comment]
Update: there is a time limit threshold around 20ms if cpu time limit is set below this threshold TL is triggered

**Comment by darbula** [comment]
Update2:

When running tests with libsandbox built from source (0.3.5) on Debian 3.2.54-2 i686 GNU/Linux with python 2.7 all tests pass except for:

```
# python test_signal.py
.....F........
======================================================================
FAIL: test_sigbus_adraln (__main__.TestSignalReceiving)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_signal.py", line 141, in test_sigbus_adraln
    self.assertEqual(s.result, Sandbox.S_RESULT_RT)
AssertionError: 1 != 6

----------------------------------------------------------------------
Ran 14 tests in 29.251s
```

**Comment by ruinshe** [comment]
+1

I ran source against ubuntu trusty 32bit, many tests failed with same result:

```
======================================================================
FAIL: test_tl_sleep (testsuite.test_quota.TestTimeQuota)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testsuite/test_quota.py", line 125, in test_tl_sleep
    self.assertEqual(s.result, Sandbox.S_RESULT_TL)
AssertionError: 2 != 5
```

**Comment by darbula** [comment]
@lyhypacm try adding access and readlink syscalls to the whitelist used in `MinimalPolicy`.
